// Copyright (c) 2026 Softside Tech Pty Ltd. All rights reserved.
// SPDX-License-Identifier: MPL-2.0

//! Raw FFI bindings to FFmpeg's libavdevice / libavformat / libavcodec /
//! libavutil for the Blackmagic DeckLink SDI device.
//!
//! Generated by bindgen at build time from [`wrapper.h`]. Everything here is
//! `unsafe` FFI — the safe surface lives in the sibling `decklink-rs` crate.
//! See that crate (and the workspace `CLAUDE.md`) for usage and the FFmpeg
//! build prerequisites (`--enable-decklink` against the Blackmagic SDK).

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
